version: '3.9'
services:
  backend:
    image: python:3.11-slim
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    working_dir: /workspace/backend
    volumes:
      - ./backend:/workspace/backend
    ports:
      - "8000:8000"
  frontend:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /workspace/frontend
    volumes:
      - ./frontend:/workspace/frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
